(+) Feature Added - Configutation (+) Feature Added - Autoupdating

diff --git a/sfinit b/sfinit
--- a/sfinit
+++ b/sfinit
@@ -2,34 +2,235 @@
 # Autor Janusz Ładecki <janusz.ladecki@gmail.com>
 clear
 
-# Define dispaly formats
-AUTHOR_FORMAT=$( tput setab 0; tput setaf 2; )
-DESCRIPTION_FORMAT=$( tput setab 7; tput bold; tput setaf 0; )
-COMMAND_FORMAT=$( tput dim; tput setaf 6; )
-COMMAND2_FORMAT=$( tput sgr0; tput setab 0; tput setaf 2; tput bold; )
-OUTPUT_FORMAT=$( tput sgr0; tput setaf 4; )
-ERR_FORMAT=$( tput sgr0; tput setaf 1; tput bold; )
-INFO_FORMAT=$( tput sgr0; tput setaf 3; tput bold; )
-SCCESS_FORMAT=$( tput sgr0; tput setaf 2; tput bold; )
-CLEAR_FORMAT=$( tput sgr0; )
-
+script_version=18.1.25
+github_url='https://github.com/szunaj13pl/shell-task-runner'
 
 echo -e ${AUTHOR_FORMAT} "by Janusz Ładecki"; tput cud 3
 
-function defineVariable(){
-    # Define custom variable
-    if [ ! -z "$variableName" ];then
-        eval "$variableName"=true
+
+function initial(){
+    
+    local scriptName=$(basename $0)
+    
+    config_folder="$HOME/.config/${scriptName}"
+    scriptServerVersion=$(mktemp -d /tmp/$scriptName.XXXXXX)
+    fileScript=$(mktemp /tmp/$scriptName.XXXXXX)
+    
+    # Use colors, but only if connected to a terminal, and that terminal supports them.
+    if which tput >/dev/null 2>&1; then
+        ncolors=$(tput colors)
+    fi
+    if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+        RED="$(tput setaf 1)"
+        GREEN="$(tput setaf 2)"
+        YELLOW="$(tput setaf 3)"
+        BLUE="$(tput setaf 4)"
+        BOLD="$(tput bold)"
+        NORMAL="$(tput sgr0)"
+
+        # Define dispaly formats
+        AUTHOR_FORMAT=$( tput setab 0; tput setaf 2; )
+        DESCRIPTION_FORMAT=$( tput setab 7; tput bold; tput setaf 0; )
+        COMMAND_FORMAT=$( tput dim; tput setaf 6; )
+        COMMAND2_FORMAT=$( tput sgr0; tput setab 0; tput setaf 2; tput bold; )
+        OUTPUT_FORMAT=$( tput sgr0; tput setaf 4; )
+        ERR_FORMAT=$( tput sgr0; tput setaf 1; tput bold; )
+        INFO_FORMAT=$( tput sgr0; tput setaf 3; tput bold; )
+        SCCESS_FORMAT=$( tput sgr0; tput setaf 2; tput bold; )
+        CLEAR_FORMAT=$( tput sgr0; )
+    else
+        RED=""
+        GREEN=""
+        YELLOW=""
+        BLUE=""
+        BOLD=""
+        NORMAL=""
     fi
     
 }
 
 
+versionCompare() {
+    if [[ $1 == $2 ]]
+    then
+        return 0
+    fi
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+    done
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            
+            return 2
+        fi
+    done
+    
+    return 0
+    
+}
+
+
+function getServerVersion(){
+    
+    git clone "$github_url" "$scriptServerVersion"
+}
+
+
+function refreshDefaultConfigFile(){
+    
+    cp "${scriptServerVersion}/default_config" "${config_folder}/default_config"\
+    && cp "${config_folder}/config" "${config_folder}/config.bak"
+    
+    if [ ! -s "${config_folder}/config" ]; then
+        cp "${config_folder}/default_config" "${config_folder}/config"
+    fi
+}
+
+
+function checkConfig(){
+    
+    if [ ! -s "${config_folder}/config" ]; then
+        
+        mkdir -p "$config_folder" || echo "Can not create default config at ${config_folder}/config" && echo "Default config was created"
+        
+        getServerVersion && refreshDefaultConfigFile
+        
+    else
+        
+        # Get variables from config
+        source "${config_folder}/config"
+    fi
+    
+}
+
+
+function checkLastUpdateDate(){
+    
+    if [ "$autoupdate" == true ] || [ ! -z ${just_update+x} ]; then
+        
+        # Get last update date from config
+        local last_update_date=$(cat "${config_folder}/config" | grep --perl-regexp  'last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})' | cut -d "=" -f 2)
+        local current_date="$(date +%F)"
+        
+        if [[ ! "$current_date" == "$last_update_date" ]] || [ "$just_update" == true ]
+        then
+            echo "Check for update" && checkOnlineVersion
+            sed -E -i "s/last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})/last_update_date\=${current_date}/" "${config_folder}/config"\
+            || echo "Missing 'last_update_date' parameter in ${config_folder}/config"
+        fi
+        
+    else
+        
+        echo -e "Autoupdate is${RED} OFF ${NORMAL}"
+    fi
+    
+}
+
+
+function checkOnlineVersion(){
+    
+    ping -c 2 Github.com 2>>/dev/null 1>&2 || (echo -e "Github.com ${RED} Unrechable ${NORMAL}" && exit 1)
+    
+    getServerVersion
+    
+    local server_version=$(cat "${scriptServerVersion}/$0" | grep --max-count=1 "script_version" |  cut -d "=" -f 2)
+    
+    versionCompare $script_version $server_version && echo -e "${YELLOW} Latest version is instaled ${NORMAL}" || (echo -e "${GREEN} New wersion on GitHub ${NORMAL}" && replaceLocalScript $server_version )
+    
+}
+
+
+function replaceLocalScript(){
+    
+    local online_version="$1"
+    local script_full_path=$(which $0 | head -n 1)
+    
+    cp "$script_full_path" "${script_full_path}.bak" \
+    && cp "${scriptServerVersion}/$0" $(dirname $script_full_path) \
+    && refreshDefaultConfigFile
+    
+    # Cleaning
+    rm -rf "$scriptServerVersion" "${script_full_path}.bak"
+    
+    $0 && exit 0
+}
+
+
+function isInstalled(){
+    
+    local packagesName="$@"
+    
+    for package in $packagesName; do
+        INSTALLED=$(dpkg-query -s "$package" 2>&1 | grep --no-messages Status )
+        if [ "$INSTALLED" != "Status: install ok installed" ]; then
+            echo -e "${NORMAL} $package ${RED}not installed ${NORMAL}"
+            sudo apt-get install -y "$package"
+        fi
+    done
+    
+}
+
+
+
+
+function defineVariable(){
+    
+    local variableName="$1"
+    shift
+    local value="$@"
+    
+    # Define custom variable
+    if [ ! -z "$variableName" ];then
+        eval "$variableName"="$value"
+    fi
+    
+}
+
+
+# function preRunCheck(){
+
+# if [ -z "$GITLAB_URL" ]; then
+#     echo -e "Please set the variable ${RED}GITLAB_URL ${NORMAL}"
+#     echo -e "\n\t Run ${YELLOW} $(basename $0) -c ${NORMAL}"
+#     exit 1
+# fi
+
+# if [ -z "$GITLAB_PRIVATE_TOKEN" ]; then
+#     echo -e "Please set the variable ${RED}GITLAB_PRIVATE_TOKEN ${NORMAL}"
+#     echo "See ${BLUE}${GITLAB_URL}/profile/account ${NORMAL}"
+#     echo -e echo -e "\n\t Run ${YELLOW} $(basename $0) -c ${NORMAL}"
+#     exit 1
+# fi
+
+# ping -c 2 "$GITLAB_URL" 2>>/dev/null 1>&2 || (echo -e "$GITLAB_URL ${RED} Unrechable ${NORMAL}" && exit 1) || exit 1
+
+# }
+
+
 function defineVarOnGrep(){
+    
+    local stringToGrep="$1"
     
     grep --count "$stringToGrep" "$tmpfile" "$outputFile" >> /dev/null \
     && echo -e ${INFO_FORMAT}"\n\t $messageOnGrep ${CLEAR_FORMAT}\n"\
-    && defineVariable "$variableName"
+    && defineVariable "$variableName" true
     
 }
 
@@ -47,7 +248,7 @@ function setResultBadge(){
         
         # Define custom variable if Grep is not set
         if [ -z "$stringToGrep" ]; then
-            defineVariable "$variableName"
+            defineVariable "$variableName" true
         fi
         
     else
@@ -146,7 +347,7 @@ function preExecute(){
                 COMMAND=$(echo "$COMMAND" | sed -u 's/bin\/console/app\/console/')
                 echo "$COMMAND"
             fi
-
+            
             executeCommand "$COMMAND" $VERBOSE
         ;;
         *)
@@ -157,25 +358,68 @@ function preExecute(){
 }
 
 
-# defineCommand		verbose|quiet[def=quiet]	exit on error(bool)[def=false]	"command"	"description"	"set variable on error to true"(VARIABLE_NAME)	"set variable on GREP FIND to true"(string)	"message on find"(String)
+# echo "$BASH_SOURCE [line: $LINENO] ${FUNCNAME[0]}"
 
-defineCommand 					verbose		false	"git pull" 														"Update project"
-defineCommand 					verbose		false	"chown $USER * --recursive" 									"Fix premissions"			"SUDO_CHOWN"
-if [ "$SUDO_CHOWN" ];then
-    defineCommand 				verbose		false	"sudo chown $USER * --recursive" 								"Fix premissions - sudo needed to set $USER as owner"
-fi
 
-# defineCommand 					quiet		true	"composer install --no-interaction --profile" 					"Install PHP dependensis"	"COMPOSER_UPDATE" "Run update"		"Composer update is recomended"
-# if [ "$COMPOSER_UPDATE" ];then
-#     defineCommand 				verbose		true	"composer update --profile"										"Install PHP dependensis - Update"
-# fi
+# Defines variables and create temp files
+initial
 
-defineCommand 					quiet		false	"npm install" 													"Install JS dependensis"
-defineCommand 					quiet		false	"php bin/console cache:clear --no-warmup" 						"Clear cache"
+usage() {
+    echo "Usage: $(basename $0) [ -c 'edit configuration' ] [ -d 'enable debuging mode' ] [ -u 'self update' ] [ <string> 'to search repository' ]" \
+    1>&2; exit 1;
+}
 
-defineCommand 					quiet		false	"php bin/console doctrine:migrations:migrate --no-interaction" 	"Make migrations"			"DOCKER_PS"		"Connection refused"	"Check if your DATABASE container is running"
-if [ "$DOCKER_PS" ];then
-    defineCommand 				verbose		false	"docker ps"														"List of all running Docker containers"
-fi
-defineCommand 					quiet		false	"php bin/console assets:install" 								"Assets"
 
+while getopts ":dcuvv" o; do
+    case "${o}" in
+        d)
+            echo "Debug mode is ON"
+            
+            set -x ;
+            set -o functrace
+        ;;
+        c)
+            if [ -e "${config_folder}/config" ]; then
+                editor "${config_folder}/config"
+            else
+                checkConfig
+                editor "${config_folder}/config"
+            fi
+            
+            exit 0
+        ;;
+        u)
+            just_update=true
+        ;;
+        v)
+            VERBOSE=$(($VERBOSE + 1))
+        ;;
+        *)
+            usage
+        ;;
+    esac
+done
+shift $((OPTIND-1))
+
+PROJECT_SEARCH_PARAM="$1"
+
+
+# Install requierd programs
+isInstalled git
+
+# Check if config exist
+checkConfig
+
+# Check for new update
+# checkLastUpdateDate
+
+[ "$just_update" == true ] && exit 0
+
+# Check if all variables ar defined and server is online
+# preRunCheck
+
+# Run script
+run
+
+# Cleaning
+rm -f "$fileScript"
