(+) Feature Added - Self Update, Config

diff --git a/sfinit b/sfinit
--- a/sfinit
+++ b/sfinit
@@ -1,53 +1,13 @@
 #!/bin/bash
+
+
 # Autor Janusz Ładecki <janusz.ladecki@gmail.com>
+
 clear
 
-script_version=18.1.25
+version=18.3.14
 github_url='https://github.com/szunaj13pl/shell-task-runner'
-
-echo -e ${AUTHOR_FORMAT} "by Janusz Ładecki"; tput cud 2
-
-
-function initial(){
-    
-    local scriptName=$(basename $0)
-    
-    config_folder="$HOME/.config/${scriptName}"
-    scriptServerVersion=$(mktemp -d /tmp/$scriptName.XXXXXX)
-    fileScript=$(mktemp /tmp/$scriptName.XXXXXX)
-    
-    # Use colors, but only if connected to a terminal, and that terminal supports them.
-    if which tput >/dev/null 2>&1; then
-        ncolors=$(tput colors)
-    fi
-    if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
-        RED="$(tput setaf 1)"
-        GREEN="$(tput setaf 2)"
-        YELLOW="$(tput setaf 3)"
-        BLUE="$(tput setaf 4)"
-        BOLD="$(tput bold)"
-        NORMAL="$(tput sgr0)"
-
-        # Define dispaly formats
-        AUTHOR_FORMAT=$( tput setab 0; tput setaf 2; )
-        DESCRIPTION_FORMAT=$( tput setab 7; tput bold; tput setaf 0; )
-        COMMAND_FORMAT=$( tput dim; tput setaf 6; )
-        COMMAND2_FORMAT=$( tput sgr0; tput setab 0; tput setaf 2; tput bold; )
-        OUTPUT_FORMAT=$( tput sgr0; tput setaf 4; )
-        ERR_FORMAT=$( tput sgr0; tput setaf 1; tput bold; )
-        INFO_FORMAT=$( tput sgr0; tput setaf 3; tput bold; )
-        SCCESS_FORMAT=$( tput sgr0; tput setaf 2; tput bold; )
-        CLEAR_FORMAT=$( tput sgr0; )
-    else
-        RED=""
-        GREEN=""
-        YELLOW=""
-        BLUE=""
-        BOLD=""
-        NORMAL=""
-    fi
-    
-}
+config_folder="$HOME/.config/task-runner"
 
 
 versionCompare() {
@@ -87,89 +47,46 @@ versionCompare() {
 }
 
 
-function getServerVersion(){
+function initial(){
     
-    git clone "$github_url" "$scriptServerVersion"
-}
-
-
-function refreshDefaultConfigFile(){
+    scriptName=$(basename $0)
+    scriptServerVersion=$(mktemp -d /tmp/$scriptName.XXXXXX)
+    script=$(mktemp /tmp/$scriptName.XXXXXX)
     
-    cp "${scriptServerVersion}/default_config" "${config_folder}/default_config"\
-    && cp "${config_folder}/config" "${config_folder}/config.bak"
-    
-    if [ ! -s "${config_folder}/config" ]; then
-        cp "${config_folder}/default_config" "${config_folder}/config"
+    # Use colors, but only if connected to a terminal, and that terminal supports them.
+    if which tput >/dev/null 2>&1; then
+        ncolors=$(tput colors)
     fi
-}
-
-
-function checkConfig(){
-    
-    if [ ! -s "${config_folder}/config" ]; then
+    if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+        RED="$(tput setaf 1)"
+        GREEN="$(tput setaf 2)"
+        YELLOW="$(tput setaf 3)"
+        BLUE="$(tput setaf 4)"
+        BOLD="$(tput bold)"
+        NORMAL="$(tput sgr0)"
         
-        mkdir -p "$config_folder" || echo "Can not create default config at ${config_folder}/config" && echo "Default config was created"
-        
-        getServerVersion && refreshDefaultConfigFile
-        
+        # Define dispaly formats
+        AUTHOR_FORMAT=$( tput setab 0; tput setaf 2; )
+        DESCRIPTION_FORMAT=$( tput setab 7; tput bold; tput setaf 0; )
+        COMMAND_FORMAT=$( tput dim; tput setaf 6; )
+        COMMAND2_FORMAT=$( tput sgr0; tput setab 0; tput setaf 2; tput bold; )
+        OUTPUT_FORMAT=$( tput sgr0; tput setaf 4; )
+        ERR_FORMAT=$( tput sgr0; tput setaf 1; tput bold; )
+        INFO_FORMAT=$( tput sgr0; tput setaf 3; tput bold; )
+        SCCESS_FORMAT=$( tput sgr0; tput setaf 2; tput bold; )
+        CLEAR_FORMAT=$( tput sgr0; )
     else
-        
-        # Get variables from config
-        source "${config_folder}/config"
+        RED=""
+        GREEN=""
+        YELLOW=""
+        BLUE=""
+        BOLD=""
+        NORMAL=""
     fi
     
-}
-
-
-function checkLastUpdateDate(){
     
-    if [ "$autoupdate" == true ] || [ ! -z ${just_update+x} ]; then
-        
-        # Get last update date from config
-        local last_update_date=$(cat "${config_folder}/config" | grep --perl-regexp  'last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})' | cut -d "=" -f 2)
-        local current_date="$(date +%F)"
-        
-        if [[ ! "$current_date" == "$last_update_date" ]] || [ "$just_update" == true ]
-        then
-            echo "Check for update" && checkOnlineVersion
-            sed -E -i "s/last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})/last_update_date\=${current_date}/" "${config_folder}/config"\
-            || echo "Missing 'last_update_date' parameter in ${config_folder}/config"
-        fi
-        
-    else
-        
-        echo -e "Autoupdate is${RED} OFF ${NORMAL}"
-    fi
+    echo -e ${AUTHOR_FORMAT} "by Janusz Ładecki"; tput cud 3
     
-}
-
-
-function checkOnlineVersion(){
-    
-    ping -c 2 Github.com 2>>/dev/null 1>&2 || (echo -e "Github.com ${RED} Unrechable ${NORMAL}" && exit 1)
-    
-    getServerVersion
-    
-    local server_version=$(cat "${scriptServerVersion}/$0" | grep --max-count=1 "script_version" |  cut -d "=" -f 2)
-    
-    versionCompare $script_version $server_version && echo -e "${YELLOW} Latest version is instaled ${NORMAL}" || (echo -e "${GREEN} New wersion on GitHub ${NORMAL}" && replaceLocalScript $server_version )
-    
-}
-
-
-function replaceLocalScript(){
-    
-    local online_version="$1"
-    local script_full_path=$(which $0 | head -n 1)
-    
-    cp "$script_full_path" "${script_full_path}.bak" \
-    && cp "${scriptServerVersion}/$0" $(dirname $script_full_path) \
-    && refreshDefaultConfigFile
-    
-    # Cleaning
-    rm -rf "$scriptServerVersion" "${script_full_path}.bak"
-    
-    $0 && exit 0
 }
 
 
@@ -188,49 +105,112 @@ function isInstalled(){
 }
 
 
+function getServerVersion(){
+    
+    git clone "$github_url" "$scriptServerVersion"
+    
+}
+
+function refreshDefaultConfigFile(){
+    
+    cp "${scriptServerVersion}/default_config" "${config_folder}/default_config"\
+    && cp "${config_folder}/config" "${config_folder}/config.bak"
+    
+    if [ ! -s "${config_folder}/config" ]; then
+        cp "${config_folder}/default_config" "${config_folder}/config"
+    fi
+}
 
 
-function defineVariable(){
+function checkConfig(){
     
-    local variableName="$1"
-    shift
-    local value="$@"
-    
-    # Define custom variable
-    if [ ! -z "$variableName" ];then
-        eval "$variableName"="$value"
+    if [ ! -s "${config_folder}/config" ]; then
+        
+        mkdir -p "$config_folder" || echo "Can not create default config at ${config_folder}/config" && echo "Default config was created"
+        
+        getServerVersion && refreshDefaultConfigFile && getConfig
+        
+    else
+        getConfig
     fi
     
 }
 
 
-# function preRunCheck(){
+function getConfig(){
+    source "${config_folder}/config"
+    
+}
 
-# if [ -z "$GITLAB_URL" ]; then
-#     echo -e "Please set the variable ${RED}GITLAB_URL ${NORMAL}"
-#     echo -e "\n\t Run ${YELLOW} $(basename $0) -c ${NORMAL}"
-#     exit 1
-# fi
 
-# if [ -z "$GITLAB_PRIVATE_TOKEN" ]; then
-#     echo -e "Please set the variable ${RED}GITLAB_PRIVATE_TOKEN ${NORMAL}"
-#     echo "See ${BLUE}${GITLAB_URL}/profile/account ${NORMAL}"
-#     echo -e echo -e "\n\t Run ${YELLOW} $(basename $0) -c ${NORMAL}"
-#     exit 1
-# fi
+function checkLastUpdateDate(){
+    
+    if [ "$autoupdate" == true ] || [ ! -z ${just_update+x} ]; then
+        
+        # Get last update date from config
+        local last_update_date=$(cat "${config_folder}/config" | grep --perl-regexp  'last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})' | cut -d "=" -f 2)
+        local current_date="$(date +%F)"
+        
+        if [[ ! "$current_date" == "$last_update_date" ]] || [ "$just_update" == true ]
+        then
+            echo "Check for update" && checkOnlineVersion
+            sed -E -i "s/last_update_date\=([0-9]{4}\-[0-9]{1,2}\-[0-9]{1,2})/last_update_date\=$current_date/" "${config_folder}/config"\
+            || echo "Missing 'last_update_date' parameter in ${config_folder}/config"
+        fi
+        
+    else
+        
+        echo -e "Autoupdate is${RED} OFF ${NORMAL}"
+    fi
+    
+}
 
-# ping -c 2 "$GITLAB_URL" 2>>/dev/null 1>&2 || (echo -e "$GITLAB_URL ${RED} Unrechable ${NORMAL}" && exit 1) || exit 1
+function checkOnlineVersion(){
+    
+    ping -c 2 Github.com 2>>/dev/null 1>&2 || (echo -e "Github.com ${RED} Unrechable ${NORMAL}" && exit 1)
+    
+    getServerVersion
+    
+    local server_version=$(cat "${scriptServerVersion}/gitlab" | grep --max-count=1 'gitlab_version' |  cut -d "=" -f 2)
+    
+    versionCompare $gitlab_version $server_version && echo -e "${YELLOW} Latest version is instaled ${NORMAL}" || (echo -e "${GREEN} New wersion on GitHub ${NORMAL}" && replaceLocalScript $server_version )
+    
+}
 
-# }
+
+function replaceLocalScript(){
+    
+    local online_version="$1"
+    local script_full_path=$(which gitlab | head -n 1)
+    
+    cp "$script_full_path" "${script_full_path}.bak" \
+    && cp "${scriptServerVersion}/gitlab" $(dirname $script_full_path) \
+    && refreshDefaultConfigFile
+    
+    # Cleaning
+    rm -rf "$scriptServerVersion" "${script_full_path}.bak"
+    
+    # scriptName && exit 0
+    ./scriptName && exit 0
+}
+
+
+# ==============  TaskRunner  ===============
+
+function defineVariable(){
+    # Define custom variable
+    if [ ! -z "$variableName" ];then
+        eval "$variableName"=true
+    fi
+    
+}
 
 
 function defineVarOnGrep(){
     
-    local stringToGrep="$1"
-    
     grep --count "$stringToGrep" "$tmpfile" "$outputFile" >> /dev/null \
     && echo -e ${INFO_FORMAT}"\n\t $messageOnGrep ${CLEAR_FORMAT}\n"\
-    && defineVariable "$variableName" true
+    && defineVariable "$variableName"
     
 }
 
@@ -248,7 +228,7 @@ function setResultBadge(){
         
         # Define custom variable if Grep is not set
         if [ -z "$stringToGrep" ]; then
-            defineVariable "$variableName" true
+            defineVariable "$variableName"
         fi
         
     else
@@ -358,11 +338,6 @@ function preExecute(){
 }
 
 
-# echo "$BASH_SOURCE [line: $LINENO] ${FUNCNAME[0]}"
-
-
-# Defines variables and create temp files
-initial
 
 usage() {
     echo "Usage: $(basename $0) [ -c 'edit configuration' ] [ -d 'enable debuging mode' ] [ -u 'self update' ] [ <string> 'to search repository' ]" \
@@ -404,22 +379,24 @@ shift $((OPTIND-1))
 PROJECT_SEARCH_PARAM="$1"
 
 
-# Install requierd programs
-isInstalled git
 
-# Check if config exist
-checkConfig
+# set -x
+
+# Defines variables and create temp files
+initial
+
+# Install requierd programs
+isInstalled git wget
 
 # Check for new update
-# checkLastUpdateDate
+checkLastUpdateDate
 
 [ "$just_update" == true ] && exit 0
 
-# Check if all variables ar defined and server is online
-# preRunCheck
+# Get config
+checkConfig
 
-# Run script
+# Run tasks
 run
 
-# Cleaning
-rm -f "$fileScript"
+# set +x
